<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows10.0.19041.0</TargetFramework>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>WinNotch.UI</RootNamespace>
    <AssemblyName>WinNotch.UI</AssemblyName>
    <NeutralLanguage>tr-TR</NeutralLanguage>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\WinNotch.Common\WinNotch.Common.csproj" />
    <ProjectReference Include="..\WinNotch.Core\WinNotch.Core.csproj" />
  </ItemGroup>
</Project>
