<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows10.0.19041.0</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>WinNotch.Core</RootNamespace>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="WinNotch.UI" />
    <InternalsVisibleTo Include="WinNotch.TrayApp" />
    <InternalsVisibleTo Include="WinNotch.Tests" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\WinNotch.Common\WinNotch.Common.csproj" />
  </ItemGroup>
</Project>
