<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows10.0.19041.0</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>WinNotch.TrayApp</RootNamespace>
    <AssemblyName>WinNotch</AssemblyName>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\WinNotch.Common\WinNotch.Common.csproj" />
    <ProjectReference Include="..\WinNotch.Core\WinNotch.Core.csproj" />
    <ProjectReference Include="..\WinNotch.UI\WinNotch.UI.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Hardcodet.NotifyIcon.Wpf" Version="1.1.0" />
  </ItemGroup>
</Project>
